//import modules libraries
import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";

//import custom components
import ClientWrapper from "components/common/ClientWrapper";
import { AuthProvider } from "contexts/AuthContext";
import { APIProvider } from "contexts/APIContext";
import { AntdNotificationProvider } from "components/common/AntdNotificationProvider";

// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";

// import Ant Design CSS
import "antd/dist/reset.css";

// import main theme scss
import "styles/theme.scss";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientWrapper>
      <html lang="en" className="expanded">
        <body className={`${publicSans.variable}`}>
          <APIProvider>
            <AuthProvider>
              <AntdNotificationProvider>
                {children}
              </AntdNotificationProvider>
            </AuthProvider>
          </APIProvider>
        </body>
      </html>
    </ClientWrapper>
  );
}
